tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary": "#6e5a4e",
        "primary-fixed-dim": "#bace95",
        "secondary-fixed": "#f9ddce",
        "background": "#fff8f5",
        "inverse-surface": "#3d2d23",
        "surface-container-low": "#fff1ea",
        "tertiary-fixed": "#e3e5c3",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "surface-container-high": "#ffe3d3",
        "on-primary": "#ffffff",
        "outline": "#75786c",
        "on-secondary-fixed": "#27180f",
        "outline-variant": "#c6c8ba",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#dcc1b2",
        "primary": "#303f15",
        "surface-tint": "#536436",
        "surface-container": "#ffeade",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#45483d",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#393c24",
        "secondary-container": "#f9ddce",
        "on-tertiary-fixed-variant": "#464930",
        "primary-fixed": "#d5eaaf",
        "on-tertiary-fixed": "#1a1d08",
        "on-background": "#27180f",
        "surface-variant": "#f9ddce",
        "inverse-primary": "#bace95",
        "on-primary-fixed-variant": "#3c4c20",
        "surface-dim": "#f0d5c5",
        "on-surface": "#27180f",
        "surface-container-highest": "#f9ddce",
        "on-secondary-fixed-variant": "#554338",
        "tertiary-fixed-dim": "#c7c9a8",
        "on-secondary-container": "#756054",
        "on-secondary": "#ffffff",
        "primary-container": "#46572a",
        "tertiary-container": "#505339",
        "on-primary-container": "#b8cc94",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#ffede4",
        "on-primary-fixed": "#121f00",
        "surface": "#fff8f5",
        "on-tertiary-container": "#c4c7a6",
        "surface-bright": "#fff8f5",
        "sage-warm": "#d4dbc5",
        "sanctuary": "#fff1ea"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
};
